name: fisco_zen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # STATO E STORAGE
  provider: ^6.1.2
  shared_preferences: ^2.5.5
  intl: any

  # FOTO & UTILITIES
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  http: ^1.2.0

  # OCR & AI
  google_mlkit_text_recognition: ^0.13.0
  firebase_vertexai: ^1.0.0

  # FIREBASE
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  firebase_crashlytics: ^4.3.10
  local_auth: ^3.0.2

# CONFIGURAZIONE ICONA APP
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  device_preview: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/ateco.json
    - assets/