name: fisco_zen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: any # 👈 Usare 'any' risolve qualsiasi problema di versione in Codespaces
  shared_preferences: ^2.5.5
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8

  # 🟢 I 3 PACCHETTI FIREBASE (Aggiunti qui sotto, allineati a 2 spazi)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ateco.json