// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-VlDHjSueK8pLBc4YDjLykLin12kYecg',
    appId: '1:78731481051:web:e7eccbe6dd84de96c1e1fe',
    messagingSenderId: '78731481051',
    projectId: 'fiscon-app',
    authDomain: 'fiscon-app.firebaseapp.com',
    storageBucket: 'fiscon-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtAmtMWtQ0WpcHNBak2khWVXSROtdRK7o',
    appId: '1:78731481051:android:f8dd3318077d8024c1e1fe',
    messagingSenderId: '78731481051',
    projectId: 'fiscon-app',
    storageBucket: 'fiscon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9kWorwDAtaYb8HQH2L3YFYHuE6MUvAvw',
    appId: '1:78731481051:ios:096f995794641d3ac1e1fe',
    messagingSenderId: '78731481051',
    projectId: 'fiscon-app',
    storageBucket: 'fiscon-app.firebasestorage.app',
    iosClientId: '78731481051-7bpk52du4ve3ajtj9ogpoee11ammc6t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiscoZen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9kWorwDAtaYb8HQH2L3YFYHuE6MUvAvw',
    appId: '1:78731481051:ios:096f995794641d3ac1e1fe',
    messagingSenderId: '78731481051',
    projectId: 'fiscon-app',
    storageBucket: 'fiscon-app.firebasestorage.app',
    iosClientId: '78731481051-7bpk52du4ve3ajtj9ogpoee11ammc6t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiscoZen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-VlDHjSueK8pLBc4YDjLykLin12kYecg',
    appId: '1:78731481051:web:06f87502b134bdb1c1e1fe',
    messagingSenderId: '78731481051',
    projectId: 'fiscon-app',
    authDomain: 'fiscon-app.firebaseapp.com',
    storageBucket: 'fiscon-app.firebasestorage.app',
  );
}
